#!/bin/bash

function createHospital() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/hospital.care.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/hospital.care.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-hospital --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-hospital.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-hospital.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-hospital.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-hospital.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/hospital.care.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy hospital's CA cert to hospital's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/hospital.care.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hospital.care.com/msp/tlscacerts/ca.crt"

  # Copy hospital's CA cert to hospital's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/hospital.care.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hospital.care.com/tlsca/tlsca.hospital.care.com-cert.pem"

  # Copy hospital's CA cert to hospital's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/hospital.care.com/ca"
  cp "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hospital.care.com/ca/ca.hospital.care.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-hospital --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-hospital --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-hospital --id.name hospitaladmin --id.secret hospitaladminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-hospital -M "${PWD}/organizations/peerOrganizations/hospital.care.com/peers/peer0.hospital.care.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hospital.care.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hospital.care.com/peers/peer0.hospital.care.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-hospital -M "${PWD}/organizations/peerOrganizations/hospital.care.com/peers/peer0.hospital.care.com/tls" --enrollment.profile tls --csr.hosts peer0.hospital.care.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/hospital.care.com/peers/peer0.hospital.care.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/hospital.care.com/peers/peer0.hospital.care.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/hospital.care.com/peers/peer0.hospital.care.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/hospital.care.com/peers/peer0.hospital.care.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/hospital.care.com/peers/peer0.hospital.care.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/hospital.care.com/peers/peer0.hospital.care.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-hospital -M "${PWD}/organizations/peerOrganizations/hospital.care.com/users/User1@hospital.care.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hospital.care.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hospital.care.com/users/User1@hospital.care.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://hospitaladmin:hospitaladminpw@localhost:7054 --caname ca-hospital -M "${PWD}/organizations/peerOrganizations/hospital.care.com/users/Admin@hospital.care.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hospital.care.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hospital.care.com/users/Admin@hospital.care.com/msp/config.yaml"
}

function createInsurance() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/insurance.care.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/insurance.care.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-insurance --tls.certfiles "${PWD}/organizations/fabric-ca/insurance/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-insurance.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-insurance.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-insurance.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-insurance.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/insurance.care.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy insurance's CA cert to insurance's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/insurance.care.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/insurance/ca-cert.pem" "${PWD}/organizations/peerOrganizations/insurance.care.com/msp/tlscacerts/ca.crt"

  # Copy insurance's CA cert to insurance's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/insurance.care.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/insurance/ca-cert.pem" "${PWD}/organizations/peerOrganizations/insurance.care.com/tlsca/tlsca.insurance.care.com-cert.pem"

  # Copy insurance's CA cert to insurance's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/insurance.care.com/ca"
  cp "${PWD}/organizations/fabric-ca/insurance/ca-cert.pem" "${PWD}/organizations/peerOrganizations/insurance.care.com/ca/ca.insurance.care.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-insurance --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/insurance/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-insurance --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/insurance/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-insurance --id.name insuranceadmin --id.secret insuranceadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/insurance/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-insurance -M "${PWD}/organizations/peerOrganizations/insurance.care.com/peers/peer0.insurance.care.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/insurance/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/insurance.care.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/insurance.care.com/peers/peer0.insurance.care.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-insurance -M "${PWD}/organizations/peerOrganizations/insurance.care.com/peers/peer0.insurance.care.com/tls" --enrollment.profile tls --csr.hosts peer0.insurance.care.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/insurance/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/insurance.care.com/peers/peer0.insurance.care.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/insurance.care.com/peers/peer0.insurance.care.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/insurance.care.com/peers/peer0.insurance.care.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/insurance.care.com/peers/peer0.insurance.care.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/insurance.care.com/peers/peer0.insurance.care.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/insurance.care.com/peers/peer0.insurance.care.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-insurance -M "${PWD}/organizations/peerOrganizations/insurance.care.com/users/User1@insurance.care.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/insurance/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/insurance.care.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/insurance.care.com/users/User1@insurance.care.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://insuranceadmin:insuranceadminpw@localhost:8054 --caname ca-insurance -M "${PWD}/organizations/peerOrganizations/insurance.care.com/users/Admin@insurance.care.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/insurance/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/insurance.care.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/insurance.care.com/users/Admin@insurance.care.com/msp/config.yaml"
}

function createPatient() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/patient.care.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/patient.care.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-patient --tls.certfiles "${PWD}/organizations/fabric-ca/patient/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-patient.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-patient.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-patient.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-patient.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/patient.care.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy patient's CA cert to patient's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/patient.care.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/patient/ca-cert.pem" "${PWD}/organizations/peerOrganizations/patient.care.com/msp/tlscacerts/ca.crt"

  # Copy patient's CA cert to patient's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/patient.care.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/patient/ca-cert.pem" "${PWD}/organizations/peerOrganizations/patient.care.com/tlsca/tlsca.patient.care.com-cert.pem"

  # Copy patient's CA cert to patient's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/patient.care.com/ca"
  cp "${PWD}/organizations/fabric-ca/patient/ca-cert.pem" "${PWD}/organizations/peerOrganizations/patient.care.com/ca/ca.patient.care.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-patient --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/patient/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-patient --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/patient/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-patient --id.name patientadmin --id.secret patientadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/patient/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-patient -M "${PWD}/organizations/peerOrganizations/patient.care.com/peers/peer0.patient.care.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/patient/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/patient.care.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/patient.care.com/peers/peer0.patient.care.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-patient -M "${PWD}/organizations/peerOrganizations/patient.care.com/peers/peer0.patient.care.com/tls" --enrollment.profile tls --csr.hosts peer0.patient.care.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/patient/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/patient.care.com/peers/peer0.patient.care.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/patient.care.com/peers/peer0.patient.care.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/patient.care.com/peers/peer0.patient.care.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/patient.care.com/peers/peer0.patient.care.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/patient.care.com/peers/peer0.patient.care.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/patient.care.com/peers/peer0.patient.care.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-patient -M "${PWD}/organizations/peerOrganizations/patient.care.com/users/User1@patient.care.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/patient/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/patient.care.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/patient.care.com/users/User1@patient.care.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://patientadmin:patientadminpw@localhost:11054 --caname ca-patient -M "${PWD}/organizations/peerOrganizations/patient.care.com/users/Admin@patient.care.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/patient/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/patient.care.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/patient.care.com/users/Admin@patient.care.com/msp/config.yaml"
}

function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/care.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/care.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/care.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/care.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/care.com/msp/tlscacerts/tlsca.care.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/care.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/care.com/tlsca/tlsca.care.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/care.com/orderers/orderer.care.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/care.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/care.com/orderers/orderer.care.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/care.com/orderers/orderer.care.com/tls" --enrollment.profile tls --csr.hosts orderer.care.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/care.com/orderers/orderer.care.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/care.com/orderers/orderer.care.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/care.com/orderers/orderer.care.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/care.com/orderers/orderer.care.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/care.com/orderers/orderer.care.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/care.com/orderers/orderer.care.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/care.com/orderers/orderer.care.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/care.com/orderers/orderer.care.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/care.com/orderers/orderer.care.com/msp/tlscacerts/tlsca.care.com-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/care.com/users/Admin@care.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/care.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/care.com/users/Admin@care.com/msp/config.yaml"
}

createHospital
createInsurance
createPatient
createOrderer